### ISSUE TITLE
Process not being returned on Index

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/Helix#255]
Context: Process targeting player's own server but started by third-party.

Should appear on Process index. Not appearing. 

See `test/process/public/index/process:15`

---

Process = Action (pause/resume/cancel) + GenericData (target ip, progress, completion date, file ID) + SensitiveData (source IP, custom)

Has full access to the process (Action + GenericData + SensitiveData):

- Players who started the process; or
- Players with root access at server who started process.

Has limited access to the process (GenericData):

- Players (who did not start process) at server that is being targeted by the process.

---

See also #252

**Comment by mememori** [comment]
Not an issue.

On `test/process/public/index/process:15` at branch `renatomassaro:crack-ssh` it's not returning the process3 because you're passing `destination_id: server.server_id` at line 37 and at line 30 but the attribute is actually `target_server_id`, not `destination_id`.

So, to fix this, change `destination_id:` to `target_server_id` at lines 30 and 37 and also change `_result_process3 = Enum.find(index.owned, &(find_by_id(&1, process3)))` to `result_process3 = Enum.find(index.targeting, &(find_by_id(&1, process3)))`
